name: Python CI PR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Bandit
        uses: dciborow/pyaction@0.0.30
        with:          
          bandit: true

      - name: Pylint
        uses: dciborow/pyaction@0.0.30
        with:
          pylint: true
          
      - name: Flake8
        uses: dciborow/pyaction@0.0.30
        with:          
          flake8: true

  testing:
    runs-on: ubuntu-latest
    steps:    
      - name: Pytest
        uses: dciborow/pyaction@0.0.30
        with:          
          pytest: true
      
