name: Python CI PR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.9'
    
      - name: Lint and Test
        uses: dciborow/pyaction@0.0.30
        with:          
          bandit: true
          flake8: true
          pytest: true

