name: Linting and Testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: dciborow/pyaction@0.0.30
        with:          
          flake8: true
          bandit: true
          
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        uses: dciborow/pyaction@0.0.30
        with:          
          pytest: true

